version: "3.7"

services:
    maven:
        image: adoptopenjdk/maven-openjdk11:latest
        container_name: maven
        working_dir: /app
        volumes:
            - ./:/app
            - ~/.m2:/root/.m2
            - ~/.aws/credentials:/root/.aws/credentials:ro
        command: mvn -B -e -C clean package

    webcrawler:
        image: ${ECR_IMAGE_URL}
        build:
            context: .
            dockerfile: Dockerfile
